### PR TITLE
Feature/inba 960 remove layer

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What does this PR do?
Removes the Grommet "Layer" which was a key component to modals... all of them.

#### Related JIRA tickets:
INBA-960

#### How should this be manually tested?
You will have to go through and trigger each of the modals and inspect. They will not be 100% the same as they were, but they will look close and should be presentable where they differ. Speak to @katebrittain and ensure if you can use staging, demo or sandbox to do side-by-side comparisons as you go. 

I recommend one of you look at it from Internet Explorer, the other Chrome. Check the following modals, and any others you can recall:
Add User (Wizard and Project Management)
Add/Select Group Users (Wizard and Project Management)
Change Project Title (Wizard and Project Management)
Change Survey Title (Wizard and Project Management)
Add Stages (Wizard, there maybe a different one for deletions)
Add Subjects (Wizard, there maybe a different one for deletions) 
New Project Title (Wizard)
Complete the Wizard (Wizard)
Forgot Modal (Login Page)
All Subjects (Subjects Tab, probably triggered by deletion) 
All Users (Users Tab, probably triggered by deletion) 
Create New Project (Anywhere for a Manager)
Task Options (Project Management)
User Profile (All Users Tab, click on the user)

### CODE REVIEW

**Comment by jmfadeley** [comment]
**Add User (Wizard and Project Management)**
_Wizard_
"Search bar should say “Add user…” or something along those lines so the user knows what the search bar does"

image
Now fixed.

**Comment by jmfadeley** [comment]
**Add/Select Group Users (Wizard and Project Management)**
"Search bar filtering not working for both sides"

This is a known issue to be handled with INBA-971.

**Comment by jmfadeley** [comment]
**Add Subjects (Wizard, there maybe a different one for deletions)**
_Wizard_
"This might just be my client, but it's still adding Tokyo and tokyo whenever i just type one or the other.. and it's not happening with any other subject. In fact, if I type London and london then only London shows up. (I recorded a screencast video I can send you on slack if you want, I'm unable to attach it in comments)"

@rileyorr please write a ticket explaining this, and include screenshots. You may assign it to Morgan or Eric at your discretion. 

"Search bar should say "Add subject..." or something so the user knows what the search bar does"
Has been appropriately changed to "Filter subjects" as it was not technically a search bar. 

image

**Comment by jmfadeley** [comment]
**Forgot Modal (Login Page)**
_Login Page_
"Clicking reset password button doesn’t indicate whether or not the action has been performed. Should we add a text alert that says “Instructions have been sent to email@mail.com!” or something?"

Yes it does. However, I think there are some .env settings missing now. 

image

**Comment by rileyorr** [comment]
@jmfadeley Thank you for making those updates!

For adding users, I can see the updated 



> **Add User (Wizard and Project Management)**
> _Wizard_
> "Search bar should say “Add user…” or something along those lines so the user knows what the search bar does"
> 
> image
> Now fixed.

Thanks for fixing that! I see the update in the Wizard, but not in Project Manager.

screen shot 2019-01-16 at 11 15 54 am

**Comment by jmfadeley** [comment]
@rileyorr Try pulling the latest. I'm seeing it:

image

**Comment by rileyorr** [comment]
@jmfadeley huh that's so strange! i did pull before i looked at it initially. is there something else i could be missing?

**Pull request merged**
