### PR TITLE
[INBA-972]  Color and Styling Overhaul

### PR DESCRIPTION
**Pull request by morleegan**
#### What does this PR do?

- adds `named_colors` and `semantic_colors` to indaba. this sets the color codes as specific values and then uses those variables throughout indaba. 

- Originally there was around 40 colors in indaba, now there is 20. 

- This although changes the core colors of indaba... so it looks different! 
we also pulled out some of the common components of the styling in indaba and created reusable utilities for them like `button`, `table`, `text-input`, etc.

- added more rules to style linting. it expects a specific order for value inputs, additionally it checks for hex/color codes that are not variables. 

#### Related JIRA tickets:
https://jira.amida.com/browse/INBA-972

#### How should this be manually tested?

Overall there needs to be testing of each page, since there was style changes everywhere. Make sure there are no errors in the build and that all the pages work. 

#### Background/Context

Feel free to look through the changes in the scss. Most of the changes are the ordering of the scss.

### CODE REVIEW

**Review by eawest2 — APPROVED** [review]
**Method**

Downloaded Repo and launched indaba stack. Navigated throughout the webpage to see if there were styles errors.

**Pages checked**

PM-

1) Login Page
2) Projects page
3) All users page
4) Message page
5) Current User Profile Page
6) User modal
7) Specific project page
8) Task options modal
9) Project Wizard
10) Survey builder

User-

1)user front page
2)User survey page

**Results**
Pages all seemed to function as per usual, with only potential minor changes that did not stand out on a quick regression test. 

**Conclusion**

This PR seems ready to merge.

**Review by jmfadeley — APPROVED** [review]
mcsaa0s

I approve, but hold off until I show Kate directly so she okays it. She needs to absorb some color shock before we spring this on her and the UMD students.

**Review by jmfadeley — CHANGES_REQUESTED** [review]
Sorry, I went back to check in IE and I noticed something happening in both IE and Chrome. $ERROR_RED isn't working... it returns black. Need to find out why.

**Review by Arghast — APPROVED** [review]
@morleegan @jmfadeley Functionality looks good in this!

**Review by jmfadeley — APPROVED** [review]
@rileyorr @morleegan @laceyIrvin I touched base with Morgan who said that the black error coloring is by design at this moment, which is fine. At this point, I'm thinking we might as well accept this. Then it'll get deployed to Indaba Staging where Lacey can take a look and spin off minor tickets if we ever return to Indaba. That way, Lacey doesn't have to spin up Indaba locally right now. 

Will merge in once Lacey approves of this.

**Comment by jmfadeley** [comment]
Don't delete branch. Leave it in case this blows up in my face.

**Pull request merged**
