### PR TITLE
Bug/inba 923 mp change stage permissions

### PR DESCRIPTION
**Pull request by morleegan**
#### What does this PR do?

Where -> PM -> stages modal. 

Permissions changes (review, complete, etc) are now disabled if the task stage has been started by an assigned person. 

Adds a tooltip to the radio button selection. When activated the tooltip displays `Stage Activities` or `activities disabled`

#### Related JIRA tickets:
https://jira.amida.com/browse/INBA-923

#### How should this be manually tested?

Use a project with multiple stages at various levels of completion. 
If one person has started the task and the date is past the start date. The Pm should see the screen below with a note about being unable to change the permission and the feature is disabled. 

#### Background/Context

I am not sure how we want to style this @rileyorr @laceyIrvin. 
does it need an error toast? 

#### Screenshots (if appropriate):
before: 
screen shot 2019-02-04 at 10 12 18 am
after
screen shot 2019-02-08 at 9 10 11 am
screen shot 2019-02-08 at 9 10 18 am

what lacey asked for: 
screen shot 2019-02-08 at 9 27 08 am

### CODE REVIEW

**Comment by jmfadeley** [comment]
I want to examine this when I've a moment so please don't merge it in until I do.

**Comment by morleegan** [comment]
@Eric - user group now has a green outline.

**Comment by rileyorr** [comment]
This is on the right track styling wise, but I think the lock icon is taking too much attention away from the content in the Stage Activities section. The icon in Lacey's mockup provides secondary information without competing with the header by using a smaller lock icon within a circle with thin line weight. However, the lock icon currently used is very large and bold so it's the first thing my eye goes to and makes the header seem like secondary information. 

I have a few possible solutions that I've talked through with @laceyIrvin. The three solutions can be seen in this screenshot:
screen shot 2019-02-08 at 10 22 01 am
1) This most closely resembles Lacey's mockup. The icon is smaller and encased in a circle with a 3px stroke to provide balance with the lock. 
2) If creating a circle with a stroke encasing the lock isn't possible, I thought this would be a possible solution. I found a resource on how to make circular backgrounds for Font Awesome icons: https://markheath.net/post/font-awesome-circle-background
3) If neither of the above options are possible, the last solution would be to simply make the icon smaller and make it a lighter grey so that it doesn't distract from the rest of the content. 

LMK if you have any questions!

**Comment by morleegan** [comment]
screen shot 2019-02-08 at 11 53 43 am
 - updated icon

**Comment by eawest2** [comment]
@morleegan 

Confirming I see the icon updates. 

No further complaints or suggestion from functionality.

**Comment by laceyIrvin** [comment]
@morleegan new icon looks good. The light grey is getting lost in the unlocked activities state so lets make the icon color: $font-color and add the opacity of 60% to the icon class as well. This will darken the font enough but not too much where its pulling all of the attention, I will approve once you push new changes. 

  &__icon {
            color: font-color;
            opacity: .6;
            margin: 0 8px 8px 8px;
        }
screenshot 2019-02-08 12 56 29

**Comment by morleegan** [comment]
@laceyIrvin done

**Comment by Arghast** [comment]
My findings: After basic user adds data to a subject, PM can still change the new stage activity by selecting a future date range (screenshot). Also, stage activities cannot be changed as soon as a user is added to a subject within a stage that is past due or due today. 
image

**Comment by morleegan** [comment]
@Arghast - check again

**Comment by Arghast** [comment]
@morleegan This looks good to merge!

**Pull request merged**
