### PR TITLE
[INBA-984] Fix allowing the user to choose the same start and end date

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What does this PR do?
Fix for the issue @Arghast found, allowing a user to choose the same start and end date for a stage.

#### Related JIRA tickets:
INBA-984

#### How should this be manually tested?
Go into Create Project Wizard. Go through the steps to add stages. Try keeping title blank and saving. You should be stopped with a red field for title, instructing you to fill it out. Then go to the start date. Tryp Ctrl + A to select it all and delete it. Attempt to submit it, and you should get a red title for the date.

Add a title and try to save, confirm you still have the red title for date. Add a date and remove the title, confirm you still have to enter the title. Try again removing end date, and the user should be forced to the start date. Fill out all info and save the stage. Click on it again and confirm all details are correct. Go to Projects, reload the page. Click on the stage and confirm its correct. 

Repeat for Project Management and be sure to do both a new stage and editing an existing one. Finally, try deleting stages to confirm the usual confirmations appear. 

#### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by Arghast** [comment]
@jmfadeley There is an issue when user tries to enter an end date before the begin date (after having begin and end dates properly filled). A silent error will occur and allow the user to click save without actually saving. 

Also, I've made the mistake of not trying to manually enter a date into the date range fields. These fields give feedback as if user could enter dates manually, but attempting this lead to the bad... and the screen goes blank.

**Comment by Arghast** [comment]
@jmfadeley Ignore the manually entering dates problem, Kate has a bug for that in the QA doc

**Comment by rileyorr** [comment]
So I think when the team decides how we want to consistently display alerts across the product we'll have to update this, but having an alert is good! However, it's not good practice to only rely on colors to communicate errors because of colorblindness. 

Normally the best practice for required fields would be to write "(Optional)" in text fields that aren't required. (https://uxdesign.cc/form-field-required-vs-optional-9b4d7cdbf400) 

I think for this case my suggestion would be to just make the alerts consistent. Instead of having the Survey Title alert in the form field put it in parenthesis next to the Survey Title header. That way it's consistent between Survey Title and Date Picker. LMK what you think about that idea!

**Comment by jmfadeley** [comment]
@rileyorr I think I can do that.

**Comment by morleegan** [comment]
cool cool James - thanks for making the error color edit and looking into `inba-935` assigning you the ticket and moving it to PR

**Pull request merged**
