### PR TITLE
Bug/INBA-976 Force task complete not updating state

### PR DESCRIPTION
**Pull request by eawest2**
#### What does this PR do?
Adjusts the force complete function of the task options modal to properly update the state when a task is set to "force complete" and thus render the completed stage.

#### Related JIRA tickets:

INBA 976

#### How should this be manually tested?

**MAKE SURE YOU HAVE THE NEWEST VERSION OF GREYSCALE, OR THIS WILL NOT WORK**

Log into a project that has several stages. Open task options on an assigned stage and set it to force complete. The completed task should now show the "done" tag after the modal closes. 

Also test by creating a new stage, assigning a user, and then setting to force complete.

### CODE REVIEW

**Review by rileyorr — APPROVED** [review]
LGTM! 
Would be nice if when the PM opens the task options after reassigning the radio buttons & headers were lightened similar to the rest of the disabled options in the modal, but that seems out of scope for the ticket. 
Nice job!

**Review by Arghast — APPROVED** [review]
@eawest2 Functionality looks good across all major browsers

**Comment by jmfadeley** [comment]
@eawest2 @Arghast @rileyorr There is now a backend PR element. Please look for INBA-976 for greyscale and test this. It's a small tweak and I'm sure it'll work fine.

**Comment by Arghast** [comment]
@jmfadeley @eawest2 LGTM!

**Pull request merged**
