### PR TITLE
[INBA-903] Changes that remove whitespace at the end of a survey and

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What does this PR do?
Checks and prevents the creation of a new project if the survey name is already in use. Also removes trailing whitespaces in both project and survey names to prevent duplications.

#### Related JIRA tickets:
INBA-903

#### How should this be manually tested?
Go to the Create Project Wizard:

- Upon seeing the modal, try to immediately click "Save". The user should be stopped with warnings about the project name and survey title being required.
- Try entering just the project name but no survey name. The user should get a warning.
- Try entering just the survey name but no project name. The user should get a warning.
- Try entering a project name that is already used but a unique survey name. The user should get a warning about the need for a unique project name.*
- Try entering a survey name that is already used but a unique project name. The user should get a warning about the need for a unique survey name.*
- Try entering a survey AND a project name that are already used. The user should get a warning about both.
-Try entering a unique survey name and unique project name and saving. It should save successfully.
- Repeat the above using the "enter" key to submit instead of hitting the "Save" button.

For both Project Management and Create Project Wizard:
Click on the Project Title Modal (the card that also reads active/inactive). Try the following scenarios:
- Confirm that the modal opens with the current project name.
- Try entering a blank name. You will be stopped because a title is required.
- Try entering a project name already in use. You will be stopped. 
- Try entering a unique name. It will be accepted.
- Repeat the above using the "enter" key to submit instead of hitting the "Save" button.

Click on the Survey Title Modal (the card that also reads active/inactive). Try the following scenarios:
- Confirm that the modal opens with the current survey name.
- Try entering a blank name. You will be stopped because a title is required.
- Try entering a survey name already in use. You will be stopped.*
- Try entering a unique name. It will be accepted.
- Repeat the above using the "enter" key to submit instead of hitting the "Save" button.

***- You may have residual data from earlier uses, because survey service does not enforce unique survey names and you may have reused titles in the past. If you see "Survey title already used" type errors but not among your existing projects, know that this problem is fairly self-correcting. You may need to wipe everything however.**

### CODE REVIEW

**Comment by Arghast** [comment]
@jmfadeley No new findings beyond what Riley pointed out. Tested in IE

**Comment by morleegan** [comment]
@jmfadeley - is this PR good to be looked at again?

**Comment by jmfadeley** [comment]
@rileyorr nope. Give me a moment to finish.

**Comment by jmfadeley** [comment]
@rileyorr @Arghast test again. Be sure to check both the create project wizard for new projects, and the survey title modal for both the Wizard and PM pages. 

It should yell at you if you try to enter a blank title and if you try to use a name of a survey already used.

**Comment by rileyorr** [comment]
@jmfadeley Tfw thinks morgan and I are the same person!! 
Works:
1. Blank project and survey titles prompts alert
2. Existing project title & new survey title prompts alert 
3. White space is removed in both project and survey titles in wizard 
4. In workflow if a unique subject title is changed to an existing one there is an alert
5. White space cannot be added before or after survey titles once project is created (alert triggered)
screen shot 2019-02-01 at 3 46 42 pm
My only worry about this is if a user accidentally adds white space before or after the title & this alert comes up, they'll think the whole title can't be used. Is there a way we can remove the white space when the user presses the save button like we do in the wizard? The same alert comes up when the user just clicks on save after opening the modal and pressing the save button.

Feedback:
1. When I'm in the wizard and I type the same project and survey titles into the text fields and click the save button my screen turns white.
2. When I'm in the wizard and I type a new project title and an existing survey title and click the save button my screen turns white. 
3. When I'm in project wizard and I create a unique project title and then try to change it to an existing project title it doesn't update, however it also doesn't give any feedback to the user why it isn't updating. I noticed this works for surveys, so we just need to add a similar alert for projects! 
4. White space can be added before and after project titles once project has been created.

**Comment by Arghast** [comment]
@jmfadeley Riley covered everything that I'm seeing as well. I'm also getting the same white screens. 
image

**Comment by jmfadeley** [comment]
@rileyorr @Arghast this ticket has convinced me to take drastic measures and rip out redux-form for these fields. Please check it on Monday.

**Comment by jmfadeley** [comment]
@Arghast @rileyorr I made very significant changes to the code. Please take note of the changed instructions above, as you have to check for both empty and unique project _and_ survey names now. Also check my footnote if you have errors regarding "survey name must be unique" despite not seeing the name used among your current projects.

**Comment by eawest2** [comment]
**Testing Method**

Downloaded Repo and ran indaba service stack. Created several new projects in line with with testing requirements.

**Results**

*Tested in Chrome*

*Project Creation Modal*
1) Project title & Survey Title throw required field if either or both are blank.
2) Unique project name error displays in appropriate field under fillable fields. 
3) Unique survey error is displayed when you attempt to save a duplicate survey name.
4) Unique survey and project name saves successfully without errors

*Project Title Modal*
1) Blank project name throws error when save is attempted.
2) Duplicate project name throws error when save is attempted.
3) Unique name change works
4) When hitting enter when you have the project title modal open, even if you have an invalid option simply closes the modal and does not execute the name change, nor display any error. It also does not execute the name change if you have a unique name, and does not display any error. The entire project page reloads when this happens.

*Survey Title Modal*
1) Blank survey name throws error when attempted.
2) Duplicate survey name throws error when attempted.
3) Unique name change works when attempted.
4) When hitting enter when you have the survey title modal open, even if you have an invalid option simply closes the modal and does not execute the name change, nor display any error. It also does not execute the name change if you have a unique name, and does not display any error. The entire project page reloads when this happens. 

**Conclusion**

It seems like the bulk functionality is just fine, however there's some event listener for the Enter key in the modal that needs to be switched from whatever it's doing to instead attempting to submit the modal. I'm going to look into it to see if I can find and correct the issue.

**Comment by jmfadeley** [comment]
@Arghast @rileyorr due to @eawest2 needing that enter key for whatever reason, I've changed the code to work when hitting the enter key. Note that I've added a final step to the testing for all the modals which involves repeating the above steps using the enter key. Please verify it's all working still.

**Pull request merged**
