### PR TITLE
Feature/inba 852 jf react router redirect from root

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What does this PR do?
Uses react-router v3 to protect certain routes. 

If the user tries to go to `http://localhost:3000/` and isn't logged in, they should be redirected to the `/login` page. If they had logged in earlier, they will be redirected to the `/tasks` page if they're a regular user and to the `/projects` page if an admin.

If a regular user tries to access any of these endpoints, they should be redirected to `/tasks`: 
`/create-new-project`
`/project`
`/project/X`
`/users`
`/subjects`

Obviously, a logged out user should be redirected to the `/login` page if they try to access these endpoints.

#### How should this be manually tested?
Please check this against IE and Chrome.

### CODE REVIEW

**Comment by Arghast** [comment]
@jmfadeley Could you fix the two conflicting file for this PR? I'll test shortly after

**Comment by Arghast** [comment]
@jmfadeley So I'm able to access the following pages When not logged in with cache cleared and reloaded. 
/messages  
/messages/new    
/profile

**Comment by jmfadeley** [comment]
@Arghast updated to cover those endpoints. Also, please check for a particular message (ie `/messages/<number>`)

**Comment by Arghast** [comment]
@jmfadeley So now I'm not able to access the following pages after signing in as a regular user. Everything else looks good
/messages     
/messages/new      
/profile

**Comment by jmfadeley** [comment]
@Arghast try now. This won't solve it if the user times out mid-usage but it'll do for the moment.

**Comment by unprofessional** [comment]
Testing those paths now work as expected for non-logged in users (redirect to /login) and regular users  and project managers (they render the proper view).

**Pull request merged**
