### PR TITLE
Feature/inba 940 check question completion

### PR DESCRIPTION
**Pull request by morleegan**
#### What does this PR do?

Survey used to send toasts if a section name or question was not filled out when hitting save. 

Now, when moving from Draft -> Published these same checks are done. if anything is blank a toast appears. 
Section names are also autofilled if a user hits save without updating the section name. 

#### Related JIRA tickets:

[INBA-940](https://jira.amida.com/browse/INBA-940)

#### How should this be manually tested?

Create a survey that is not completely filled out in the project wizard and the normal place. 
Try to change to draft and see errors.

#### Screenshots (if appropriate):

### CODE REVIEW

**Comment by morleegan** [comment]
@rileyorr - fixed.

**Comment by jmfadeley** [comment]
@rileyorr we could just turn off the autoClose so it remains until clicked on.

**Comment by rileyorr** [comment]
@jmfadeley I think that's a great solution! I was about to comment about how I think it's still a little too long. 
Also this is a side note but I think it would be beneficial to have one of the company's writers take a look at Indaba to see if our language is clear and understandable. Just something to keep in mind as we begin redesigning components!

**Comment by morleegan** [comment]
@rileyorr @jmfadeley - toast closes on x button instead.

**Comment by jmfadeley** [comment]
@rileyorr @morleegan Looks good. Final suggestion: The `UNFILLED_SURVEY` section simply reads "Finish creating survey before publishing." I would change it to "Please finish creating the survey before publishing. Don't forget to save your progress." Otherwise, the user can fill out all questions and be confused like so:

image

**Comment by jmfadeley** [comment]
@morleegan spoke to Riley and Lacey. Go ahead and update that language as mentioned above, and this PR is good to go. We will do another PR to draw attention to the "Save Progress" button later.

**Pull request merged**
