### PR TITLE
Bug/inba 975 weighted value row delete error

### PR DESCRIPTION
**Pull request by jmfadeley**
#### What does this PR do?

Fixes an issue where deleting a weighted value row was broken. For example, this is before I delete the middle row:
image

And this is after I delete the middle row (weighted value 3):
image

Note that "Text three" moved up but the weighted value was "3" instead of "4", which it should have been. 

#### Related JIRA tickets:
INBA-975

#### How should this be manually tested?

1. Go into survey builder.
2. Selected a question with a weighted value (Checkbox, Multiple Choice, Dropdown).
3. You can check with one row, but you should check with multiple rows. 
4. Click "Weighted Value Question"
5. Enter values into each of the boxes that appear. Make these values different (ie 1 thru 10) so you can see the difference.
6. Delete a row at the top or midstream. The one below it should move up and the weighted value it was assigned should replace it:

Also, please try to break a "scale" question, which was slightly refactored. Minimum values SHOULD NOT go over a maximum value (instead being reset to one less than the max).

### CODE REVIEW

**Comment by jmfadeley** [comment]
@rileyorr @Arghast cleared to test again. Do me a favor Reedy and check this on IE as well. There's something I don't trust there.

**Comment by rileyorr** [comment]
@jmfadeley LGTM!

**Comment by jmfadeley** [comment]
1) The survey building isn't autosaving by design. This is in discussion on how to better approach. You have to click the "Save Progress" button for the stuff to persist. 
2) That's a visual. I would make a new ticket for it. 
3) That's just how it is with Microsoft stuff. I would make a separate ticket if we want to look into that.

**Comment by Arghast** [comment]
@jmfadeley 1. These user case issues are happening after hitting the "save button". 
I'll report 2 and ask about 3.

**Comment by jmfadeley** [comment]
Nope. If there is no option, it shouldn't be saved even if there is a weighted value. Bring it up to Lacey and Riley to see if they want the data explanations changed in another PR, but point 1 isn't going to be addressed here.

**Pull request merged**
