### PR TITLE
Feature/inba 973 ro mp buttons

### PR DESCRIPTION
**Pull request by morleegan**
#### What does this PR do?
- Refactors scss to have a the semantic/color values selected by Riley and Lacey. 
- Refactors all buttons to only use 2 buttons designed by Riley. 
- Refactors other small things in scss and some color fixes I found. 

#### Related JIRA tickets:
https://jira.amida.com/browse/INBA-972
https://jira.amida.com/browse/INBA-973
https://jira.amida.com/browse/INBA-974

#### How should this be manually tested?
Go through the entire suite of indaba and look at buttons for stying issues. 
biggest changes was to the scss so there shouldn't be any functionality issues. 

#### Background/Context
we're trying to incrementally fix indaba and the first step is to using only the colors chosen. 
this is another refactor ticket Riley is working on. 

#### Screenshots (if appropriate):

### CODE REVIEW

**Comment by rileyorr** [comment]
Thank you for the feedback @laceyIrvin! I agree that 16px is too much padding, so I played around and want to compare 8px with 12px.
screen shot 2019-01-17 at 9 42 53 am
8px
screen shot 2019-01-17 at 9 41 11 am
12px

My only concerns with 8px padding is the text not having enough breathing room (especially since it's in all caps) and usability on iPad. I also think the buttons might be grabbing a lot of optical attention right now because they're the only elements we've updated. Let me know what you think! Once we decide on the padding, I'll move onto the look for the expand, collapse, & invite buttons.

**Comment by Arghast** [comment]
@morleegan Getting this error trying to stand up the client 
image

**Comment by morleegan** [comment]
@Arghast - fixed

**Comment by jmfadeley** [comment]
image
Wut.

**Comment by jmfadeley** [comment]
In Survey Builder, please get rid of the "Expand" and "Collapse" buttons as their functionality doesn't work and we're probably not going to add it for a while. 

Do this only for Survey Builder, not for Task Review. Those buttons work, although they need adjustment.
image

Second, in Survey Builder, Click on the circled plus button for the Menu. Those buttons could use some space between them, and a little less padding on the right.
image

**Comment by jmfadeley** [comment]
Create a question with meta data. Note that the button looks... like, a button. 

image

**Comment by jmfadeley** [comment]
I thought we were hiding the reset password button for user profiles?

image

**Comment by Arghast** [comment]
@morleegan The old buttons had boxes around them and changed to a darker color on mouse rollover. Only some of the new buttons have boxes around them and only the buttons with boxes change on mouse rollover. I'm wondering if this is an oversight or if we could improve the new buttons by adding more user feedback to the buttons with no surrounding box.

image
image
Old buttons for comparison
image

**Comment by morleegan** [comment]
@Arghast - that is a design question for @laceyIrvin and @rileyorr. 

Can you pull your code? I'm not seeing the right font but you should have it from the import

**Comment by Arghast** [comment]
@morleegan Just to note: after pulling the latest I'm still seeing the "skinny" on PC.

Changing the filter on a survey changed the styling of the plus sign to look like this:
image

**Comment by jmfadeley** [comment]
@Arghast I already checked in a fix for that in another PR.

**Comment by jmfadeley** [comment]
@Arghast also try stopping and restarting your app. Depending on how the CSS is built, it may only pull the font from Google during the build, and deliver it with the bundle.

**Comment by jmfadeley** [comment]
@morleegan @rileyorr I'm overruled. Don't merge until after Friday, and ask even then.

**Pull request merged**
